clean:
  script: "make clean && make distclean"

make:
  script: "source /opt/davy/1.0/environment-setup-cortexa9hf-vfp-neon-davy-linux-gnueabi && qmake && make -j4"

install:
  script: "cp Yamaha/bin/Yamaha /tmp"
