/*
 * 初始化仪表信息模块
 */
function initializeInstrumentModel(listmodelArray,data) {
    listmodelArray[0].setProperty(0,"name",data.InstrumentFrame.input_ctrl_01);
    listmodelArray[0].setProperty(1,"name",data.InstrumentFrame.input_ctrl_02);
    listmodelArray[0].setProperty(2,"name",data.InstrumentFrame.input_ctrl_03);
    listmodelArray[0].setProperty(3,"name",data.InstrumentFrame.input_ctrl_04);
    listmodelArray[0].setProperty(4,"name",data.InstrumentFrame.input_ctrl_05);
    listmodelArray[0].setProperty(5,"name",data.InstrumentFrame.input_ctrl_06);
    listmodelArray[0].setProperty(6,"name",data.InstrumentFrame.input_ctrl_07);
    listmodelArray[0].setProperty(7,"name",data.InstrumentFrame.input_ctrl_08);
    listmodelArray[0].setProperty(8,"name",data.InstrumentFrame.input_ctrl_09);
    listmodelArray[0].setProperty(9,"name",data.InstrumentFrame.input_ctrl_10);
    listmodelArray[1].setProperty(0,"name",data.InstrumentFrame.input_ctrl_11);
    listmodelArray[1].setProperty(1,"name",data.InstrumentFrame.input_ctrl_12);
    listmodelArray[1].setProperty(2,"name",data.InstrumentFrame.input_ctrl_13);
    listmodelArray[1].setProperty(3,"name",data.InstrumentFrame.input_ctrl_14);
    listmodelArray[1].setProperty(4,"name",data.InstrumentFrame.input_ctrl_15);
    listmodelArray[1].setProperty(5,"name",data.InstrumentFrame.input_ctrl_16);
    listmodelArray[1].setProperty(6,"name",data.InstrumentFrame.input_ctrl_17);
    listmodelArray[1].setProperty(7,"name",data.InstrumentFrame.input_ctrl_18);
    listmodelArray[1].setProperty(8,"name",data.InstrumentFrame.input_ctrl_19);
    listmodelArray[1].setProperty(9,"name",data.InstrumentFrame.input_ctrl_20);
    listmodelArray[2].setProperty(0,"name",data.InstrumentFrame.input_ctrl_21);
    listmodelArray[2].setProperty(1,"name",data.InstrumentFrame.input_ctrl_22);
    listmodelArray[2].setProperty(2,"name",data.InstrumentFrame.input_ctrl_23);
    listmodelArray[2].setProperty(3,"name",data.InstrumentFrame.input_ctrl_24);
    listmodelArray[2].setProperty(4,"name",data.InstrumentFrame.input_ctrl_25);
    listmodelArray[2].setProperty(5,"name",data.InstrumentFrame.input_ctrl_26);
    listmodelArray[2].setProperty(6,"name",data.InstrumentFrame.input_ctrl_27);
    listmodelArray[2].setProperty(7,"name",data.InstrumentFrame.input_ctrl_28);
    listmodelArray[2].setProperty(8,"name",data.InstrumentFrame.input_ctrl_29);
    listmodelArray[2].setProperty(9,"name",data.InstrumentFrame.input_ctrl_30);
    listmodelArray[3].setProperty(0,"name",data.InstrumentFrame.input_ctrl_31);
    listmodelArray[3].setProperty(1,"name",data.InstrumentFrame.input_ctrl_32);
    listmodelArray[3].setProperty(2,"name",data.InstrumentFrame.input_ctrl_33);
    listmodelArray[3].setProperty(3,"name",data.InstrumentFrame.input_ctrl_34);
    listmodelArray[3].setProperty(4,"name",data.InstrumentFrame.input_ctrl_35);
    listmodelArray[3].setProperty(5,"name",data.InstrumentFrame.input_ctrl_36);
    listmodelArray[3].setProperty(6,"name",data.InstrumentFrame.input_ctrl_37);
    listmodelArray[3].setProperty(7,"name",data.InstrumentFrame.input_ctrl_38);
    listmodelArray[3].setProperty(8,"name",data.InstrumentFrame.input_ctrl_39);
    listmodelArray[3].setProperty(9,"name",data.InstrumentFrame.input_ctrl_40);
}
/*
 * 初始化仪表信息前模块
 */
function initializeBeforeModule(listmodelArray,data) {
    listmodelArray[0].setProperty(0,"name",data.ModuleFrontFrame.switch_01);
    listmodelArray[0].setProperty(1,"name",data.ModuleFrontFrame.switch_02);
    listmodelArray[0].setProperty(2,"name",data.ModuleFrontFrame.switch_03);
    listmodelArray[0].setProperty(3,"name",data.ModuleFrontFrame.switch_04);
    listmodelArray[0].setProperty(4,"name",data.ModuleFrontFrame.switch_05);
    listmodelArray[0].setProperty(5,"name",data.ModuleFrontFrame.switch_06);
    listmodelArray[0].setProperty(6,"name",data.ModuleFrontFrame.switch_07);
    listmodelArray[0].setProperty(7,"name",data.ModuleFrontFrame.switch_08);
    listmodelArray[0].setProperty(8,"name",data.ModuleFrontFrame.switch_09);
    listmodelArray[0].setProperty(9,"name",data.ModuleFrontFrame.switch_10);
    listmodelArray[1].setProperty(0,"name",data.ModuleFrontFrame.switch_11);
    listmodelArray[1].setProperty(1,"name",data.ModuleFrontFrame.switch_12);
    listmodelArray[1].setProperty(2,"name",data.ModuleFrontFrame.switch_13);
    listmodelArray[1].setProperty(3,"name",data.ModuleFrontFrame.switch_14);
    listmodelArray[1].setProperty(4,"name",data.ModuleFrontFrame.switch_15);
    listmodelArray[1].setProperty(5,"name",data.ModuleFrontFrame.switch_16);
    listmodelArray[1].setProperty(6,"name",data.ModuleFrontFrame.switch_17);
    listmodelArray[1].setProperty(7,"name",data.ModuleFrontFrame.switch_18);
    listmodelArray[1].setProperty(8,"name",data.ModuleFrontFrame.switch_19);
    listmodelArray[1].setProperty(9,"name",data.ModuleFrontFrame.switch_20);
    listmodelArray[2].setProperty(0,"name",data.ModuleFrontFrame.switch_21);
    listmodelArray[2].setProperty(1,"name",data.ModuleFrontFrame.switch_22);
    listmodelArray[2].setProperty(2,"name",data.ModuleFrontFrame.switch_23);
    listmodelArray[2].setProperty(3,"name",data.ModuleFrontFrame.switch_24);
    listmodelArray[2].setProperty(4,"name",data.ModuleFrontFrame.switch_25);
    listmodelArray[2].setProperty(5,"name",data.ModuleFrontFrame.switch_26);
    listmodelArray[2].setProperty(6,"name",data.ModuleFrontFrame.switch_27);
    listmodelArray[2].setProperty(7,"name",data.ModuleFrontFrame.switch_28);
    listmodelArray[2].setProperty(8,"name",data.ModuleFrontFrame.switch_29);
    listmodelArray[2].setProperty(9,"name",data.ModuleFrontFrame.switch_30);
    listmodelArray[3].setProperty(0,"name",data.ModuleFrontFrame.switch_31);
    listmodelArray[3].setProperty(1,"name",data.ModuleFrontFrame.switch_32);
    listmodelArray[3].setProperty(2,"name",data.ModuleFrontFrame.switch_33);
    listmodelArray[3].setProperty(3,"name",data.ModuleFrontFrame.switch_34);
    listmodelArray[3].setProperty(4,"name",data.ModuleFrontFrame.switch_35);
    listmodelArray[3].setProperty(5,"name",data.ModuleFrontFrame.switch_36);
    listmodelArray[3].setProperty(6,"name",data.ModuleFrontFrame.switch_37);
    listmodelArray[3].setProperty(7,"name",data.ModuleFrontFrame.switch_38);
    listmodelArray[3].setProperty(8,"name",data.ModuleFrontFrame.switch_39);
    listmodelArray[3].setProperty(9,"name",data.ModuleFrontFrame.switch_40);
}
/*
 * 初始化仪表信息中模块
 */
function initializeCenterModule(listmodelArray,data) {
    listmodelArray[0].setProperty(0,"name",data.ModuleMiddleFrame.switch_01);
    listmodelArray[0].setProperty(1,"name",data.ModuleMiddleFrame.switch_02);
    listmodelArray[0].setProperty(2,"name",data.ModuleMiddleFrame.switch_03);
    listmodelArray[0].setProperty(3,"name",data.ModuleMiddleFrame.switch_04);
    listmodelArray[0].setProperty(4,"name",data.ModuleMiddleFrame.switch_05);
    listmodelArray[0].setProperty(5,"name",data.ModuleMiddleFrame.switch_06);
    listmodelArray[0].setProperty(6,"name",data.ModuleMiddleFrame.switch_07);
    listmodelArray[0].setProperty(7,"name",data.ModuleMiddleFrame.switch_08);
    listmodelArray[0].setProperty(8,"name",data.ModuleMiddleFrame.switch_09);
    listmodelArray[0].setProperty(9,"name",data.ModuleMiddleFrame.switch_10);
    listmodelArray[1].setProperty(0,"name",data.ModuleMiddleFrame.switch_11);
    listmodelArray[1].setProperty(1,"name",data.ModuleMiddleFrame.switch_12);
    listmodelArray[1].setProperty(2,"name",data.ModuleMiddleFrame.switch_13);
    listmodelArray[1].setProperty(3,"name",data.ModuleMiddleFrame.switch_14);
    listmodelArray[1].setProperty(4,"name",data.ModuleMiddleFrame.switch_15);
    listmodelArray[1].setProperty(5,"name",data.ModuleMiddleFrame.switch_16);
    listmodelArray[1].setProperty(6,"name",data.ModuleMiddleFrame.switch_17);
    listmodelArray[1].setProperty(7,"name",data.ModuleMiddleFrame.switch_18);
    listmodelArray[1].setProperty(8,"name",data.ModuleMiddleFrame.switch_19);
    listmodelArray[1].setProperty(9,"name",data.ModuleMiddleFrame.switch_20);
    listmodelArray[2].setProperty(0,"name",data.ModuleMiddleFrame.switch_21);
    listmodelArray[2].setProperty(1,"name",data.ModuleMiddleFrame.switch_22);
    listmodelArray[2].setProperty(2,"name",data.ModuleMiddleFrame.switch_23);
    listmodelArray[2].setProperty(3,"name",data.ModuleMiddleFrame.switch_24);
    listmodelArray[2].setProperty(4,"name",data.ModuleMiddleFrame.switch_25);
    listmodelArray[2].setProperty(5,"name",data.ModuleMiddleFrame.switch_26);
    listmodelArray[2].setProperty(6,"name",data.ModuleMiddleFrame.switch_27);
    listmodelArray[2].setProperty(7,"name",data.ModuleMiddleFrame.switch_28);
    listmodelArray[2].setProperty(8,"name",data.ModuleMiddleFrame.switch_29);
    listmodelArray[2].setProperty(9,"name",data.ModuleMiddleFrame.switch_30);
    listmodelArray[3].setProperty(0,"name",data.ModuleMiddleFrame.switch_31);
    listmodelArray[3].setProperty(1,"name",data.ModuleMiddleFrame.switch_32);
    listmodelArray[3].setProperty(2,"name",data.ModuleMiddleFrame.switch_33);
    listmodelArray[3].setProperty(3,"name",data.ModuleMiddleFrame.switch_34);
    listmodelArray[3].setProperty(4,"name",data.ModuleMiddleFrame.switch_35);
    listmodelArray[3].setProperty(5,"name",data.ModuleMiddleFrame.switch_36);
    listmodelArray[3].setProperty(6,"name",data.ModuleMiddleFrame.switch_37);
    listmodelArray[3].setProperty(7,"name",data.ModuleMiddleFrame.switch_38);
    listmodelArray[3].setProperty(8,"name",data.ModuleMiddleFrame.switch_39);
    listmodelArray[3].setProperty(9,"name",data.ModuleMiddleFrame.switch_40);
}
/*
 * 初始化仪表信息后模块
 */
function initializeAfterModule(listmodelArray,data) {
    listmodelArray[0].setProperty(0,"name",data.ModuleBackFrame.switch_01);
    listmodelArray[0].setProperty(1,"name",data.ModuleBackFrame.switch_02);
    listmodelArray[0].setProperty(2,"name",data.ModuleBackFrame.switch_03);
    listmodelArray[0].setProperty(3,"name",data.ModuleBackFrame.switch_04);
    listmodelArray[0].setProperty(4,"name",data.ModuleBackFrame.switch_05);
    listmodelArray[0].setProperty(5,"name",data.ModuleBackFrame.switch_06);
    listmodelArray[0].setProperty(6,"name",data.ModuleBackFrame.switch_07);
    listmodelArray[0].setProperty(7,"name",data.ModuleBackFrame.switch_08);
    listmodelArray[0].setProperty(8,"name",data.ModuleBackFrame.switch_09);
    listmodelArray[0].setProperty(9,"name",data.ModuleBackFrame.switch_10);
    listmodelArray[1].setProperty(0,"name",data.ModuleBackFrame.switch_11);
    listmodelArray[1].setProperty(1,"name",data.ModuleBackFrame.switch_12);
    listmodelArray[1].setProperty(2,"name",data.ModuleBackFrame.switch_13);
    listmodelArray[1].setProperty(3,"name",data.ModuleBackFrame.switch_14);
    listmodelArray[1].setProperty(4,"name",data.ModuleBackFrame.switch_15);
    listmodelArray[1].setProperty(5,"name",data.ModuleBackFrame.switch_16);
    listmodelArray[1].setProperty(6,"name",data.ModuleBackFrame.switch_17);
    listmodelArray[1].setProperty(7,"name",data.ModuleBackFrame.switch_18);
    listmodelArray[1].setProperty(8,"name",data.ModuleBackFrame.switch_19);
    listmodelArray[1].setProperty(9,"name",data.ModuleBackFrame.switch_20);
    listmodelArray[2].setProperty(0,"name",data.ModuleBackFrame.switch_21);
    listmodelArray[2].setProperty(1,"name",data.ModuleBackFrame.switch_22);
    listmodelArray[2].setProperty(2,"name",data.ModuleBackFrame.switch_23);
    listmodelArray[2].setProperty(3,"name",data.ModuleBackFrame.switch_24);
    listmodelArray[2].setProperty(4,"name",data.ModuleBackFrame.switch_25);
    listmodelArray[2].setProperty(5,"name",data.ModuleBackFrame.switch_26);
    listmodelArray[2].setProperty(6,"name",data.ModuleBackFrame.switch_27);
    listmodelArray[2].setProperty(7,"name",data.ModuleBackFrame.switch_28);
    listmodelArray[2].setProperty(8,"name",data.ModuleBackFrame.switch_29);
    listmodelArray[2].setProperty(9,"name",data.ModuleBackFrame.switch_30);
    listmodelArray[3].setProperty(0,"name",data.ModuleBackFrame.switch_31);
    listmodelArray[3].setProperty(1,"name",data.ModuleBackFrame.switch_32);
    listmodelArray[3].setProperty(2,"name",data.ModuleBackFrame.switch_33);
    listmodelArray[3].setProperty(3,"name",data.ModuleBackFrame.switch_34);
    listmodelArray[3].setProperty(4,"name",data.ModuleBackFrame.switch_35);
    listmodelArray[3].setProperty(5,"name",data.ModuleBackFrame.switch_36);
    listmodelArray[3].setProperty(6,"name",data.ModuleBackFrame.switch_37);
    listmodelArray[3].setProperty(7,"name",data.ModuleBackFrame.switch_38);
    listmodelArray[3].setProperty(8,"name",data.ModuleBackFrame.switch_39);
    listmodelArray[3].setProperty(9,"name",data.ModuleBackFrame.switch_40);
}
