#pragma once

#include "CarMsgData.hpp"

//Car 信息 状态数据
struct CarMsgWorkerStateData {
    carfox::CarMsgData<quint8> tmpVersion = carfox::CarMsgData<quint8>(0);
    carfox::CarMsgData<qint8> themeMode = carfox::CarMsgData<qint8>(-1);
    carfox::CarMsgData<qint32> carMode = carfox::CarMsgData<qint32>(-1);             //汽车模式： 1. igOn 2. alarmOn 3. igOff

    //通用帧数据
    carfox::CarMsgData<qint32> dateTime = carfox::CarMsgData<qint32>(-1);          //系统时间
    carfox::CarMsgData<float> carSpeed = carfox::CarMsgData<float>(-1);          //车速
    carfox::CarMsgData<float> rpm = carfox::CarMsgData<float>(-1);               //转速
    carfox::CarMsgData<float> totalVoltage = carfox::CarMsgData<float>(-1);      //总电压, 0 V
    carfox::CarMsgData<float> totalCurrent = carfox::CarMsgData<float>(-1);      //总电流, 0 A
    carfox::CarMsgData<qint32> gear = carfox::CarMsgData<qint32>(-1);              //档位, 0
    carfox::CarMsgData<quint32> odo = carfox::CarMsgData<quint32>(-1);             //总里程, 0 Km
    carfox::CarMsgData<float> trip = carfox::CarMsgData<float>(-1);                //小计里程, 0.0 Km
    carfox::CarMsgData<float> soc = carfox::CarMsgData<float>(-1);             //系统SOC,0 %
    carfox::CarMsgData<float> apVol1 = carfox::CarMsgData<float>(-1);              //气压1, 0.00 Mpa,协议收到为Kpa，需要除以1000
    carfox::CarMsgData<float> apVol2 = carfox::CarMsgData<float>(-1);              //气压2, 0.00 Mpa,协议收到为Kpa，需要除以1000
    carfox::CarMsgData<qint32> moterControlTemp = carfox::CarMsgData<qint32>(-1);  //电机控制器温度, 0 ℃
    carfox::CarMsgData<qint32> moterTemp = carfox::CarMsgData<qint32>(-1);         //电机温度, 0 ℃
    carfox::CarMsgData<qint32> battery = carfox::CarMsgData<qint32>(-1);           //蓄电池电压
    carfox::CarMsgData<qint32> spn = carfox::CarMsgData<qint32>(-1);               //SPN值
    carfox::CarMsgData<qint32> engineWaterTemp = carfox::CarMsgData<qint32>(-1);   //发动机水温
    carfox::CarMsgData<qint32> ureaLevel = carfox::CarMsgData<qint32>(-1);          //尿素液位
    carfox::CarMsgData<quint32> faultLevel = carfox::CarMsgData<quint32>(-1);       //故障等级
    carfox::CarMsgData<qint32> faultCode = carfox::CarMsgData<qint32>(-1);          //故障代码
    carfox::CarMsgData<quint32> oilLevel = carfox::CarMsgData<quint32>(-1);         //油量百分比
    carfox::CarMsgData<float> engineOilPressure = carfox::CarMsgData<float>(-1);    //发动机机油压力
    carfox::CarMsgData<float> aloneBatteryLowVoltage = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> aloneBatteryHighVoltage = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<qint32> batteryHighTemperature = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> batteryLowTemperature = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<float> batteryPackEnergy = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<qint32> velocityRatio = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<bool> buzzerStatus = carfox::CarMsgData<bool>(-1);
    //设置模块信息
    carfox::CarMsgData<bool> tripMilesClear = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> checkMilesClear = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<qint32> upgradeMsgId = carfox::CarMsgData<qint32>(-1);        //升级消息ID
    carfox::CarMsgData<QString> upgradeMsgCtx = carfox::CarMsgData<QString>("");   //升级消息内容
    carfox::CarMsgData<bool> closeBuzzerClear = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> checkCloseBuzzerClear = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> checkDateTimeSetting = carfox::CarMsgData<bool>(-1);
    //控制系统信息
    carfox::CarMsgData<float> motorInVoltage = carfox::CarMsgData<float>(-1);		   //电机输入电压, 0 V
    carfox::CarMsgData<float> motorInCurrent = carfox::CarMsgData<float>(-1);		   //电机输入电流, 0 A
    carfox::CarMsgData<qint32> motorTemp = carfox::CarMsgData<qint32>(-1);			   //电机温度, 0 ℃
    carfox::CarMsgData<qint32> motorControllerTemp = carfox::CarMsgData<qint32>(-1); //电机控制器温度, 0 ℃
    carfox::CarMsgData<qint32> carVcuMode = carfox::CarMsgData<qint32>(-1);			   //整车模式, 0
    carfox::CarMsgData<double> version = carfox::CarMsgData<double>(-1);			   //程序版本, 0.00
    carfox::CarMsgData<qint32> carLife = carfox::CarMsgData<qint32>(-1);			   //整车控制器Life, 0
    carfox::CarMsgData<float> accelPedalPercent = carfox::CarMsgData<float>(-1); 	   //加速踏板百分比,0.0 %
    carfox::CarMsgData<float> brakePedalPercent = carfox::CarMsgData<float>(-1);	   //制动踏板百分比,0.0 %
    carfox::CarMsgData<quint32> din1 = carfox::CarMsgData<quint32>(-1);			       //数字量输入1, 00000000（2进制显示）
    carfox::CarMsgData<quint32> din2 = carfox::CarMsgData<quint32>(-1);			       //数字量输入2, 00000000（2进制显示）
    carfox::CarMsgData<quint32> din3 = carfox::CarMsgData<quint32>(-1);			       //数字量输入3, 00000000（2进制显示）
    carfox::CarMsgData<quint32> dout1 = carfox::CarMsgData<quint32>(-1);			   //数字量输出1, 00000000（2进制显示）
    carfox::CarMsgData<quint32> dout2 = carfox::CarMsgData<quint32>(-1);			   //数字量输出2, 00000000（2进制显示）
    carfox::CarMsgData<quint32> dout3 = carfox::CarMsgData<quint32>(-1);			   //数字量输出3, 00000000（2进制显示）
    carfox::CarMsgData<quint32> driveSystemStatus = carfox::CarMsgData<quint32>(-1);
    carfox::CarMsgData<quint32> driveMotorStatus = carfox::CarMsgData<quint32>(-1);
    carfox::CarMsgData<quint32> mechanicalBrakeStatus = carfox::CarMsgData<quint32>(-1);
    carfox::CarMsgData<bool> keyAcc = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> keyOn = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> highVoltageInterLock = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> highVoltagePowerUp = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> airCompressorWork = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> boosterPumpWork = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<float> airCompressorMotorSpeed = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> steeringAssistMotorSpeed = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<qint32> steeringAssistMotorTemp = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> airCompressorMotorTemp = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> airCompressorControlTemp = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> steeringControlDeviceTemp = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<float> airPress3 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> airPress4 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> airPress5 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<qint32> highestAlarmGrade = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> faultAlarmSituation = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> driveGearsMode = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> bduSwitch = carfox::CarMsgData<qint32>(-1);

    //仪表信息
    carfox::CarMsgData<bool> inputCtrl01 = carfox::CarMsgData<bool>(-1);        //左转向开关
    carfox::CarMsgData<bool> inputCtrl02 = carfox::CarMsgData<bool>(-1);        //备用
    carfox::CarMsgData<bool> inputCtrl03 = carfox::CarMsgData<bool>(-1);        //备用
    carfox::CarMsgData<bool> inputCtrl04 = carfox::CarMsgData<bool>(-1);        //钥匙ST开关
    carfox::CarMsgData<bool> inputCtrl05 = carfox::CarMsgData<bool>(-1);        //右转向开关
    carfox::CarMsgData<bool> inputCtrl06 = carfox::CarMsgData<bool>(-1);        //小灯开关
    carfox::CarMsgData<bool> inputCtrl07 = carfox::CarMsgData<bool>(-1);        //远光灯开关
    carfox::CarMsgData<bool> inputCtrl08 = carfox::CarMsgData<bool>(-1);        //近光灯开关
    carfox::CarMsgData<bool> inputCtrl09 = carfox::CarMsgData<bool>(-1);        //前雾灯开关
    carfox::CarMsgData<bool> inputCtrl10 = carfox::CarMsgData<bool>(-1);        //后雾灯开关
    carfox::CarMsgData<bool> inputCtrl11 = carfox::CarMsgData<bool>(-1);        //备用
    carfox::CarMsgData<bool> inputCtrl12 = carfox::CarMsgData<bool>(-1);        //广告灯箱开关
    carfox::CarMsgData<bool> inputCtrl13 = carfox::CarMsgData<bool>(-1);        //备用
    carfox::CarMsgData<bool> inputCtrl14 = carfox::CarMsgData<bool>(-1);        //雨刮低档开关
    carfox::CarMsgData<bool> inputCtrl15 = carfox::CarMsgData<bool>(-1);        //雨刮间歇档开关
    carfox::CarMsgData<bool> inputCtrl16 = carfox::CarMsgData<bool>(-1);        //雨刮高档开关
    carfox::CarMsgData<bool> inputCtrl17 = carfox::CarMsgData<bool>(-1);        //备用
    carfox::CarMsgData<bool> inputCtrl18 = carfox::CarMsgData<bool>(-1);        //备用
    carfox::CarMsgData<bool> inputCtrl19 = carfox::CarMsgData<bool>(-1);        //路牌开关
    carfox::CarMsgData<bool> inputCtrl20 = carfox::CarMsgData<bool>(-1);        //前门开开关
    carfox::CarMsgData<bool> inputCtrl21 = carfox::CarMsgData<bool>(-1);        //雨刮喷水档开关
    carfox::CarMsgData<bool> inputCtrl22 = carfox::CarMsgData<bool>(-1);        //备用
    carfox::CarMsgData<bool> inputCtrl23 = carfox::CarMsgData<bool>(-1);        //备用
    carfox::CarMsgData<bool> inputCtrl24 = carfox::CarMsgData<bool>(-1);        //备用
    carfox::CarMsgData<bool> inputCtrl25 = carfox::CarMsgData<bool>(-1);        //备用
    carfox::CarMsgData<bool> inputCtrl26 = carfox::CarMsgData<bool>(-1);        //中门关开关
    carfox::CarMsgData<bool> inputCtrl27 = carfox::CarMsgData<bool>(-1);        //中门开开关
    carfox::CarMsgData<bool> inputCtrl28 = carfox::CarMsgData<bool>(-1);        //前门关开关
    carfox::CarMsgData<bool> inputCtrl29 = carfox::CarMsgData<bool>(-1);        //燃油量过低报警
    carfox::CarMsgData<bool> inputCtrl30 = carfox::CarMsgData<bool>(-1);        //备用
    carfox::CarMsgData<bool> inputCtrl31 = carfox::CarMsgData<bool>(-1);        //备用
    carfox::CarMsgData<bool> inputCtrl32 = carfox::CarMsgData<bool>(-1);        //备用
    carfox::CarMsgData<bool> inputCtrl33 = carfox::CarMsgData<bool>(-1);        //危险报警
    carfox::CarMsgData<bool> inputCtrl34 = carfox::CarMsgData<bool>(-1);        //电源唤醒
    carfox::CarMsgData<bool> inputCtrl35 = carfox::CarMsgData<bool>(-1);        //钥匙ON
    //前模块信息
    carfox::CarMsgData<float> frontOutputCurrent01 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> frontOutputCurrent02 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> frontOutputCurrent03 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> frontOutputCurrent04 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> frontOutputCurrent05 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> frontOutputCurrent06 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> frontOutputCurrent07 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> frontOutputCurrent08 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> frontOutputCurrent09 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> frontOutputCurrent10 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> frontOutputCurrent11 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> frontOutputCurrent12 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> frontOutputCurrent13 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> frontOutputCurrent14 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> frontOutputCurrent15 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<qint32> frontOutputFault01 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> frontOutputFault02 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> frontOutputFault03 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> frontOutputFault04 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> frontOutputFault05 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> frontOutputFault06 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> frontOutputFault07 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> frontOutputFault08 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> frontOutputFault09 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> frontOutputFault10 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> frontOutputFault11 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> frontOutputFault12 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> frontOutputFault13 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> frontOutputFault14 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> frontOutputFault15 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<bool> frontSwitch01 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> frontSwitch02 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> frontSwitch03 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> frontSwitch04 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> frontSwitch05 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> frontSwitch06 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> frontSwitch07 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> frontSwitch08 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> frontSwitch09 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> frontSwitch10 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> frontSwitch11 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> frontSwitch12 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> frontSwitch13 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> frontSwitch14 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> frontSwitch15 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> frontSwitch16 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<float> frontAnalogInput01 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> frontAnalogInput02 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<qint32> frontHzInput = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> frontSpeedInput = carfox::CarMsgData<qint32>(-1);
    //中模块信息
    carfox::CarMsgData<float> middleOutputCurrent01 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> middleOutputCurrent02 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> middleOutputCurrent03 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> middleOutputCurrent04 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> middleOutputCurrent05 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> middleOutputCurrent06 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> middleOutputCurrent07 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> middleOutputCurrent08 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> middleOutputCurrent09 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> middleOutputCurrent10 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> middleOutputCurrent11 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> middleOutputCurrent12 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> middleOutputCurrent13 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> middleOutputCurrent14 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> middleOutputCurrent15 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<qint32> middleOutputFault01 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> middleOutputFault02 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> middleOutputFault03 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> middleOutputFault04 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> middleOutputFault05 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> middleOutputFault06 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> middleOutputFault07 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> middleOutputFault08 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> middleOutputFault09 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> middleOutputFault10 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> middleOutputFault11 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> middleOutputFault12 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> middleOutputFault13 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> middleOutputFault14 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> middleOutputFault15 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<bool> middleSwitch01 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> middleSwitch02 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> middleSwitch03 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> middleSwitch04 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> middleSwitch05 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> middleSwitch06 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> middleSwitch07 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> middleSwitch08 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> middleSwitch09 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> middleSwitch10 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> middleSwitch11 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> middleSwitch12 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> middleSwitch13 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> middleSwitch14 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> middleSwitch15 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> middleSwitch16 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<float> middleAnalogInput01 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> middleAnalogInput02 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<qint32> middleHzInput = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> middleSpeedInput = carfox::CarMsgData<qint32>(-1);
    //后模块信息
    carfox::CarMsgData<float> backOutputCurrent01 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> backOutputCurrent02 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> backOutputCurrent03 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> backOutputCurrent04 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> backOutputCurrent05 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> backOutputCurrent06 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> backOutputCurrent07 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> backOutputCurrent08 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> backOutputCurrent09 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> backOutputCurrent10 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> backOutputCurrent11 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> backOutputCurrent12 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> backOutputCurrent13 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> backOutputCurrent14 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> backOutputCurrent15 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<qint32> backOutputFault01 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> backOutputFault02 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> backOutputFault03 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> backOutputFault04 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> backOutputFault05 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> backOutputFault06 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> backOutputFault07 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> backOutputFault08 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> backOutputFault09 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> backOutputFault10 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> backOutputFault11 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> backOutputFault12 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> backOutputFault13 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> backOutputFault14 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> backOutputFault15 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<bool> backSwitch01 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> backSwitch02 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> backSwitch03 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> backSwitch04 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> backSwitch05 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> backSwitch06 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> backSwitch07 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> backSwitch08 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> backSwitch09 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> backSwitch10 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> backSwitch11 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> backSwitch12 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> backSwitch13 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> backSwitch14 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> backSwitch15 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> backSwitch16 = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<float> backAnalogInput01 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> backAnalogInput02 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<qint32> backHzInput = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> backSpeedInput = carfox::CarMsgData<qint32>(-1);
    //警告提示
    carfox::CarMsgData<qint32> warningId = carfox::CarMsgData<qint32>(-1);
    //发动机系统信息
    carfox::CarMsgData<float> engineFuelConsumption = carfox::CarMsgData<float>(-1);   	//发动机油耗, 0.00 L/H
    carfox::CarMsgData<qint32> engineLoad = carfox::CarMsgData<qint32>(-1);			        //发动机负荷, 0 %
    carfox::CarMsgData<float> engineTargetThrottle = carfox::CarMsgData<float>(-1);		//发动机目标油门, 0.0 %
    carfox::CarMsgData<float> engineActualThrottle = carfox::CarMsgData<float>(-1);		//发动机实际油门, 0.0 %
    carfox::CarMsgData<qint32> engineInletTemperature = carfox::CarMsgData<qint32>(-1);	//发动机进气温度, 0 ℃
    //辅助系统信息
    carfox::CarMsgData<float> oilPumpDcacWoutputCurrent = carfox::CarMsgData<float>(-1);      //油泵DC/AC W相输出电流, 0 A
    carfox::CarMsgData<float> oilPumpDcacVoutputCurrent = carfox::CarMsgData<float>(-1);      //油泵DC/AC V相输出电流, 0 A
    carfox::CarMsgData<float> oilPumpDcacUoutputCurrent = carfox::CarMsgData<float>(-1);      //油泵DC/AC U相输出电流, 0 A
    carfox::CarMsgData<qint32> radiatorTemperature = carfox::CarMsgData<qint32>(-1);              //散热器温度, 0 ℃
    //TCU系统信息
    carfox::CarMsgData<qint32> actualClutchPosition = carfox::CarMsgData<qint32>(-1);		//离合实际位置, 0
    carfox::CarMsgData<quint32> tcuFaultCode = carfox::CarMsgData<quint32>(-1);			//TCU故障信息, 00000000（2进制显示）
    carfox::CarMsgData<qint32> axisRpm = carfox::CarMsgData<qint32>(-1);                   //变速箱输出轴转速, 0 RPM
    carfox::CarMsgData<qint32> fmi = carfox::CarMsgData<qint32>(-1);                        //FMI值, 0
    carfox::CarMsgData<qint32> cm = carfox::CarMsgData<qint32>(-1);                         //CM值, 0
    carfox::CarMsgData<quint32> oc = carfox::CarMsgData<quint32>(-1);			        	//OC, 0（16进制显示）
    //电池管理系统
    carfox::CarMsgData<float> batMaxChargeCurrent = carfox::CarMsgData<float>(-1);		//最大允许充电电流,, 0.0 A
    carfox::CarMsgData<float> batMaxDischargeCurrent = carfox::CarMsgData<float>(-1);	//最大允许放电电流,, 0.0 A
    carfox::CarMsgData<float> batAverageVoltage = carfox::CarMsgData<float>(-1);          //单体平均电压, 0.00 V
    carfox::CarMsgData<quint32> batStatus1 = carfox::CarMsgData<quint32>(-1);              //电池状态1, 00000000（2进制显示）
    carfox::CarMsgData<quint32> batStatus2 = carfox::CarMsgData<quint32>(-1);              //电池状态2, 00000000（2进制显示）
    carfox::CarMsgData<quint32> batStatus3 = carfox::CarMsgData<quint32>(-1);              //电池状态3, 00000000（2进制显示）
    carfox::CarMsgData<float> irmOhmPositive = carfox::CarMsgData<float>(-1);             //总正绝缘阻值, 0 KΩ
    carfox::CarMsgData<float> irmOhmNegative = carfox::CarMsgData<float>(-1);             //总负绝缘阻值, 0 KΩ
    carfox::CarMsgData<float> batMaxVoltage = carfox::CarMsgData<float>(-1);              //单体最高电压, 0.00 V
    carfox::CarMsgData<float> batMinVoltage = carfox::CarMsgData<float>(-1);              //单体最低电压, 0.00 V
    carfox::CarMsgData<float> batteryHighestTemp = carfox::CarMsgData<float>(-1);         //单体最高温度, 0.0 ℃
    carfox::CarMsgData<float> bmsVersion = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<qint32> bmsModuleAmount = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> bmsLife = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> batteryPackHighestTemp = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> batteryPackMinTemp = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<float> batteryManagePackEnergy = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<qint32> bmsControlStatus = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> batAmount = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> rechargeStatus = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> tempStyletAmount = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> outletPositiveTemp = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> outletNegativeTemp = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> powerBatteryType = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> powerBatteryRecharge = carfox::CarMsgData<qint32>(-1);
    //电池组电压信息
    carfox::CarMsgData<quint32> addrNumberVoltage = carfox::CarMsgData<quint32>(-1);
    carfox::CarMsgData<float> addrNumberVoltageValue = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<quint32> boxNumberVoltage = carfox::CarMsgData<quint32>(-1);
    //carfox::CarMsgData<QVariantMap> voltageInfo = carfox::CarMsgData<QVariantMap>(-1);
    //电池组温度信息
    carfox::CarMsgData<quint32> addrNumberTemp = carfox::CarMsgData<quint32>(-1);
    carfox::CarMsgData<float> addrNumberTempValue = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<quint32> boxNumberTemp = carfox::CarMsgData<quint32>(-1);
    //carfox::CarMsgData<QVariantMap> tempInfo = carfox::CarMsgData<QVariantMap>(-1);
    //空调系统信息
    carfox::CarMsgData<quint32> acFaultCode = carfox::CarMsgData<quint32>(-1);            //空调故障代码, 00000000（2进制显示）
    carfox::CarMsgData<quint32> acFanStatus = carfox::CarMsgData<quint32>(-1);            //空调风机状态, 00000000（2进制显示）
    carfox::CarMsgData<quint32> acWorkStatus = carfox::CarMsgData<quint32>(-1);           //空调工作状态, 00000000（2进制显示）
    carfox::CarMsgData<quint32> acLife = carfox::CarMsgData<quint32>(-1);                  //空调Life, 0
    carfox::CarMsgData<qint32> acOutTemp = carfox::CarMsgData<qint32>(-1);                //车外实际温度, 0 ℃
    carfox::CarMsgData<qint32> acInTemp = carfox::CarMsgData<qint32>(-1);                 //车内实际温度, 0 ℃
    carfox::CarMsgData<qint32> acSetTemp = carfox::CarMsgData<qint32>(-1);                //设定温度, 0 ℃
    carfox::CarMsgData<quint32> acRefrigereReq = carfox::CarMsgData<quint32>(-1);         //空调制冷请求, 00000000（2进制显示）
    //DCDC状态信息
    carfox::CarMsgData<float> dcLowVoltage = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> dcLowCurrent = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<qint32> dcTemp = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> dcStatus2 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<bool> dcUndervoltage = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> dcOvervoltage = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> dcOverheating = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> dcShortCircuit = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> dcWorkStatus = carfox::CarMsgData<bool>(-1);
    //符号片显示
    carfox::CarMsgData<bool> lampKeyOn = carfox::CarMsgData<bool>(-1);                     //钥匙ON开关(总电源指示)
    carfox::CarMsgData<bool> lampAirFilter = carfox::CarMsgData<bool>(-1);                 //空滤指示
    carfox::CarMsgData<bool> lampAsr = carfox::CarMsgData<bool>(-1);                        //ASR指示
    carfox::CarMsgData<bool> lampHighVoltageMaintenance = carfox::CarMsgData<bool>(-1);   //高压检修
    carfox::CarMsgData<bool> lampDefroster = carfox::CarMsgData<bool>(-1);                  //除霜器
    carfox::CarMsgData<bool> lampDryere = carfox::CarMsgData<bool>(-1);                     //干燥器
    carfox::CarMsgData<bool> lampAbs = carfox::CarMsgData<bool>(-1);                        //ABS指示
    carfox::CarMsgData<bool> lampAc = carfox::CarMsgData<bool>(-1);                         //AC空调指示
    carfox::CarMsgData<bool> powerSupply = carfox::CarMsgData<bool>(-1);                //Power模式符号片(纯电动模式 or 混动模式 or 插电模式)
    carfox::CarMsgData<bool> powerPlugInMode = carfox::CarMsgData<bool>(-1);            //power插电模式
    carfox::CarMsgData<bool> powerByvridMode = carfox::CarMsgData<bool>(-1);            //power混动模式
    carfox::CarMsgData<bool> climbingMode = carfox::CarMsgData<bool>(-1);                   //爬坡模式符号片
    carfox::CarMsgData<bool> diagnosticMode = carfox::CarMsgData<bool>(-1);                 //诊断模式符号片
    carfox::CarMsgData<bool> lampTurnLeft = carfox::CarMsgData<bool>(-1);         	       //左转向
    carfox::CarMsgData<bool> lampTurnRight = carfox::CarMsgData<bool>(-1);       	       //右转向
    carfox::CarMsgData<bool> lampDoubleFlash = carfox::CarMsgData<bool>(-1);      	       //双闪开启
    carfox::CarMsgData<bool> lampFrontFog = carfox::CarMsgData<bool>(-1);         	       //前雾灯
    carfox::CarMsgData<bool> lampRearFog = carfox::CarMsgData<bool>(-1);         	       //后雾灯
    carfox::CarMsgData<bool> lampHighBeam = carfox::CarMsgData<bool>(-1);        	       //远光灯
    carfox::CarMsgData<bool> lampHeadLight = carfox::CarMsgData<bool>(-1);       	       //近光灯
    carfox::CarMsgData<bool> lampReverseGear = carfox::CarMsgData<bool>(-1);               //倒车灯
    carfox::CarMsgData<bool> lampPositionLight = carfox::CarMsgData<bool>(-1);             //位置灯
    carfox::CarMsgData<bool> lampGate1 = carfox::CarMsgData<bool>(-1);            	       //前门开
    carfox::CarMsgData<bool> lampGate2 = carfox::CarMsgData<bool>(-1);                      //中门开
    carfox::CarMsgData<bool> lampRearDoorOpen = carfox::CarMsgData<bool>(-1);             //后舱门开指示
    carfox::CarMsgData<bool> lampBrake = carfox::CarMsgData<bool>(-1);                      //刹车制动
    carfox::CarMsgData<bool> lampParkingBrake = carfox::CarMsgData<bool>(-1);              //驻车制动
    carfox::CarMsgData<bool> lampLeftLowAirPressure = carfox::CarMsgData<bool>(-1);      //左气压低报警
    carfox::CarMsgData<bool> lampRightLowAirPressure = carfox::CarMsgData<bool>(-1);     //右气压低报警
    carfox::CarMsgData<bool> lampLeftShoeWear = carfox::CarMsgData<bool>(-1);             //左前摩擦片(刹车蹄片)报警
    carfox::CarMsgData<bool> lampRightShoeWear = carfox::CarMsgData<bool>(-1);            //右前摩擦片(刹车蹄片)报警
    carfox::CarMsgData<bool> lampChargeConfirm = carfox::CarMsgData<bool>(-1);             //充电确认
    carfox::CarMsgData<bool> lampBatteryMainContact = carfox::CarMsgData<bool>(-1);       //电池主接触器KT
    carfox::CarMsgData<bool> lampWaterTempHigh = carfox::CarMsgData<bool>(-1);            //水温高报警
    carfox::CarMsgData<bool> lampWaterLevelLow = carfox::CarMsgData<bool>(-1);            //水位低指示
    carfox::CarMsgData<bool> lampLowServiceWl = carfox::CarMsgData<bool>(-1);             //轻微故障报警STOP
    carfox::CarMsgData<bool> lampHeavyStopWl = carfox::CarMsgData<bool>(-1);              //重大故障报警STOP
    carfox::CarMsgData<bool> lampSeriousStopWl = carfox::CarMsgData<bool>(-1);            //严重故障报警STOP
    carfox::CarMsgData<bool> lampOilLevelLow = carfox::CarMsgData<bool>(-1);              //油量低报警
    carfox::CarMsgData<bool> lampOilPressureLow = carfox::CarMsgData<bool>(-1);           //机油压力低
    carfox::CarMsgData<bool> lampEngineFault = carfox::CarMsgData<bool>(-1);               //发动机故障
    carfox::CarMsgData<bool> lampMotorOutOfService = carfox::CarMsgData<bool>(-1);       //24V发电机未工作
    carfox::CarMsgData<bool> lampMoterFireIgon = carfox::CarMsgData<bool>(-1);            //发电机点火指示
    carfox::CarMsgData<bool> lampAfterTreat = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> lampWarningLed = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> airPress1Lamp = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> airPress2Lamp = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> airPress3Lamp = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> airPress4Lamp = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> airPress5Lamp = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> powerDoorsOpen = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> powerBatteryCutOff = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> seatbeltNotFastened = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> forwardGear = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> neutralGear = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> reverseGear = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> electronicInSlope = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> ascd = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> ready = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> powerAccumulatorsChargeStatus = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> cableConnect = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> controlMotorOverheating = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> powerAccumulatorsFault = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> driverSystemFault = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> severityInsulationFault = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> slightInsulationFault = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> motorPowerLimitation = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> bmsAlarm = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> socLowAram = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> safetySystemAlarm = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> leftDoorsOpenAlarm = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> rightDoorsOpenAlarm = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> barrierFreeMarchReach = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> gateChargeOpen = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> driverSeatAlarm = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> ecasSystemFaultLed = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> ecasAlarmLed = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> ecasKneelingStatusLed = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> ecasSpecialHeightLed = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> dropOffDoorbell = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> wait = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> frontDoorExigencyAlarm = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> middleDoorExigencyAlarm = carfox::CarMsgData<bool>(-1);
    carfox::CarMsgData<bool> stop = carfox::CarMsgData<bool>(-1);
    //胎压模块信息
    carfox::CarMsgData<float> frontLeftTirePress = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> fronRightTirePress = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> backLeftTirePress1 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> backRightTirePress1 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> backLeftTirePress2 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<float> backRightTirePress2 = carfox::CarMsgData<float>(-1);
    carfox::CarMsgData<qint32> frontLeftTireTemp = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> frontRightTireTemp = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> backLeftTireTemp1 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> backRightTireTemp1 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> backLeftTireTemp2 = carfox::CarMsgData<qint32>(-1);
    carfox::CarMsgData<qint32> backRightTireTemp2 = carfox::CarMsgData<qint32>(-1);
    //控制系统诊断信息
    carfox::CarMsgData<bool> driveFaultAlarm = carfox::CarMsgData<bool>(-1); //驱动系统故障报警
    carfox::CarMsgData<bool> controlOvervoltageAlarm = carfox::CarMsgData<bool>(-1); //驱动控制器过压报警
    carfox::CarMsgData<bool> controlUndervoltageAlarm = carfox::CarMsgData<bool>(-1); //驱动控制器欠压报警
    carfox::CarMsgData<bool> controlEncodingFault = carfox::CarMsgData<bool>(-1); //驱动控制器编码故障
    carfox::CarMsgData<bool> controlHighTempAlarm = carfox::CarMsgData<bool>(-1); //驱动控制器高温报警
    carfox::CarMsgData<bool> controlHighTempAbortAlarm = carfox::CarMsgData<bool>(-1); //驱动控制器高温截止报警
    carfox::CarMsgData<bool> controlMainContactorFault = carfox::CarMsgData<bool>(-1); //驱动控制器主接触器故障
    carfox::CarMsgData<bool> controlOvercurrentAlarm = carfox::CarMsgData<bool>(-1); //驱动控制器过流报警
    carfox::CarMsgData<bool> motorHighTempAlarm = carfox::CarMsgData<bool>(-1); //驱动电机高温报警
    carfox::CarMsgData<bool> motorHigtTempAbortAlarm = carfox::CarMsgData<bool>(-1); //驱动电机高温截止报警
    carfox::CarMsgData<bool> motorRotaryFault = carfox::CarMsgData<bool>(-1); //驱动电机旋变故障报警
    carfox::CarMsgData<bool> controlMotorPowerLimitation = carfox::CarMsgData<bool>(-1); //驱动电机功率受限报警
    carfox::CarMsgData<bool> motorRotaryLimitation = carfox::CarMsgData<bool>(-1); //驱动电机转矩受限报警
    carfox::CarMsgData<bool> motorWaterTempOvertop = carfox::CarMsgData<bool>(-1); //驱动电机水温过高报警
    carfox::CarMsgData<bool> acceleratorPedalFault = carfox::CarMsgData<bool>(-1); //加速踏板信号值异常报警
    carfox::CarMsgData<bool> brakePedalFaule = carfox::CarMsgData<bool>(-1); //刹车踏板信号值异常报警
    carfox::CarMsgData<bool> seatbeltAlarm = carfox::CarMsgData<bool>(-1); //安全带报警
    carfox::CarMsgData<bool> seatSwitchAlarm = carfox::CarMsgData<bool>(-1); //座椅开关报警
    carfox::CarMsgData<bool> controlRightDoorsOpenAlarm = carfox::CarMsgData<bool>(-1); //右侧舱门开启报警
    carfox::CarMsgData<bool> controlLeftDoorsOpenAlarm = carfox::CarMsgData<bool>(-1); //左侧舱门开启报警
    carfox::CarMsgData<bool> chauffeurDoorsNotClose = carfox::CarMsgData<bool>(-1); //司机门未关报警
    carfox::CarMsgData<bool> highTensionSwitchOpen = carfox::CarMsgData<bool>(-1); //高压开关门开启报警
    carfox::CarMsgData<bool> chargeDoorOpen = carfox::CarMsgData<bool>(-1); //充电门开启报警
    carfox::CarMsgData<bool> safetyDoorOpen = carfox::CarMsgData<bool>(-1); //安全门开启报警
    carfox::CarMsgData<bool> lowVoltageSwitchOpen = carfox::CarMsgData<bool>(-1); //低压开关门开启报警
    carfox::CarMsgData<bool> absSystemFault = carfox::CarMsgData<bool>(-1); //ABS系统故障
    carfox::CarMsgData<bool> airCompressorControlHighTemp = carfox::CarMsgData<bool>(-1); //空压机控制器高温报警
    carfox::CarMsgData<bool> airCompressorMotorHighTemp = carfox::CarMsgData<bool>(-1); //空压机电机高温报警
    carfox::CarMsgData<bool> boosterPumpControlHighTemp = carfox::CarMsgData<bool>(-1); //助力泵控制器高温报警
    carfox::CarMsgData<bool> boosterPumpMotorHighTemp = carfox::CarMsgData<bool>(-1); //助力泵电机高温报警
    carfox::CarMsgData<float> vcuVersion = carfox::CarMsgData<float>(-1); //VCU程序版本号，0.0
    carfox::CarMsgData<qint32> vcuLife = carfox::CarMsgData<qint32>(-1); //VCU系统Life值
    //动力电池诊断系统信息
    carfox::CarMsgData<bool> batVoltageMaxAlarm = carfox::CarMsgData<bool>(-1); //单体电压过高报警
    carfox::CarMsgData<bool> batVoltageMaxAbortAlarm = carfox::CarMsgData<bool>(-1); //单体电压过高截止报警
    carfox::CarMsgData<bool> batVoltageMinAlarm = carfox::CarMsgData<bool>(-1); //单体电压过低报警
    carfox::CarMsgData<bool> batVoltageMinAbortAlarm = carfox::CarMsgData<bool>(-1); //单体电压过低截止报警
    carfox::CarMsgData<bool> chargeCurrentMaxAlarm = carfox::CarMsgData<bool>(-1); //峰值充电电流过大
    carfox::CarMsgData<bool> dischargeCurrentMaxAlarm = carfox::CarMsgData<bool>(-1); //峰值放电电流过大
    carfox::CarMsgData<bool> dischargeCurrentMaxAbortAlarm = carfox::CarMsgData<bool>(-1); //峰值放电电流过大截止报警
    carfox::CarMsgData<bool> dischargeCurrentTempMinAlarm = carfox::CarMsgData<bool>(-1); //电池放电温度过低报警
    carfox::CarMsgData<bool> dischargeCurrentTempMinAbortAlarm = carfox::CarMsgData<bool>(-1); //电池放电温度过低截止报警
    carfox::CarMsgData<bool> chargeCurrentTempMaxAlarm = carfox::CarMsgData<bool>(-1); //电池充电温度过高报警
    carfox::CarMsgData<bool> chargeCurrentTempMaxAbortAlarm = carfox::CarMsgData<bool>(-1); //电池充电温度过高截止报警
    carfox::CarMsgData<bool> batTempMaxAlarm = carfox::CarMsgData<bool>(-1); //电池温度过高报警
    carfox::CarMsgData<bool> batTempMaxAbortAlarm = carfox::CarMsgData<bool>(-1); //电池温度过高截止报警
    carfox::CarMsgData<bool> dropoutVoltageMaxAlarm = carfox::CarMsgData<bool>(-1); //单体电压压差过大报警
    carfox::CarMsgData<bool> dropoutVoltageMaxAbortAlarm = carfox::CarMsgData<bool>(-1); //单体电压压差过大截止报警
    carfox::CarMsgData<bool> chargeVoltageMaxAlarm = carfox::CarMsgData<bool>(-1); //电池充电电压过高
    carfox::CarMsgData<bool> batTempDifferentAlarm = carfox::CarMsgData<bool>(-1); //动力电池温度差异报警
    carfox::CarMsgData<bool> batChargeTempMinAbortAlarm = carfox::CarMsgData<bool>(-1); //电池充电温度过低截止报警
    carfox::CarMsgData<bool> batChargeTempMinAlarm = carfox::CarMsgData<bool>(-1); //动力电池充电温度过低报警
    carfox::CarMsgData<bool> socMinAlarm = carfox::CarMsgData<bool>(-1); //动力电池SOC过低报警
    carfox::CarMsgData<bool> socMaxAlarm = carfox::CarMsgData<bool>(-1); //动力电池SOC过高报警
    carfox::CarMsgData<bool> batModuleCommunicationFail = carfox::CarMsgData<bool>(-1); //动力电池模块通讯失效
    carfox::CarMsgData<bool> bmsSystemFault = carfox::CarMsgData<bool>(-1); //BMS系统故障
    carfox::CarMsgData<bool> batteryFault = carfox::CarMsgData<bool>(-1); //动力蓄电池故障
    carfox::CarMsgData<bool> energyRecoveryCurrentMaxAlarm = carfox::CarMsgData<bool>(-1); //制动能量回收电流过大报警
    carfox::CarMsgData<bool> energyRecoveryVoltageMaxAlarm = carfox::CarMsgData<bool>(-1); //制动能量回收单体电压过高报警
    carfox::CarMsgData<bool> energyRecoveryVoltageMaxAbort = carfox::CarMsgData<bool>(-1); //制动能量回收单体电压过高截止报警
    carfox::CarMsgData<bool> energyRecoveryCancel = carfox::CarMsgData<bool>(-1); //取消制动能量回收功能
    carfox::CarMsgData<bool> socJumpAlarm = carfox::CarMsgData<bool>(-1); //SOC跳变报警
    carfox::CarMsgData<bool> mismatchingAlarm = carfox::CarMsgData<bool>(-1); //可充电储能系统不匹配报警
    carfox::CarMsgData<bool> vehicleMountedTypeMax = carfox::CarMsgData<bool>(-1); //车载储能装置类型过压报警
    carfox::CarMsgData<bool> vehicleMountedTypeMin = carfox::CarMsgData<bool>(-1); //车载储能装置类型欠压报警
    carfox::CarMsgData<bool> vehicleMountedTypeOvercharge = carfox::CarMsgData<bool>(-1); //车载储能装置类型过充
};

struct CarMSgWorkerSignalData {
    bool mKey1 = false;    // byte10: 0
    bool mKey2 = false;    // byte10: 1
    bool mKey3 = false;    // byte10: 2
    bool mKey4 = false;    // byte10: 3
    uint mKeyStatus = 0;

    int mPreviousPressedKey = 0;
    int mPreviousKeyPressedTime = 0;
    bool isFirstSignal = false;
};
